### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Andi-Lo** [danielscherzer/MMPROG#1]
Hallo Daniel,

ich bekomme beim Kompilieren in Visuall Studio folgenden Fehler: "ShaderCompileException wurde nicht behandelt". ATI Grafikkarte

![compileerror](https://cloud.githubusercontent.com/assets/7545568/10617838/d8c84a4e-776c-11e5-9535-6a33b16849b3.PNG)

Beim Ausführen der fertig gebauten shaderForm.exe erhalte ich:

![exeerror](https://cloud.githubusercontent.com/assets/7545568/10617872/16ff580c-776d-11e5-9d87-c0dbe9286fd0.PNG)

Gibts dafür eine Lösung?

**Comment by danielscherzer** [comment]
hallo,

hab ne neue version vom shaderform erstellt, die dieses problem hoffentlich 
behebt und mehr fehler info ausgibt. probier mal bitte aus!

lg
daniel

Am 20.10.2015 um 20:57 schrieb Andreas Lorer:
> Hallo Daniel,
>
> ich bekomme beim Kompilieren in Visuall Studio folgenden Fehler: "ShaderCompileException wurde nicht behandelt". ATI Grafikkarte
>
> ![compileerror](https://cloud.githubusercontent.com/assets/7545568/10617838/d8c84a4e-776c-11e5-9535-6a33b16849b3.PNG)
>
> Beim Ausführen der fertig gebauten shaderForm.exe erhalte ich:
>
> ![exeerror](https://cloud.githubusercontent.com/assets/7545568/10617872/16ff580c-776d-11e5-9d87-c0dbe9286fd0.PNG)
>
> Gibts dafür eine Lösung?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/danielscherzer/MMPROG/issues/1
>

-- 
-- Daniel Scherzer ----------------------------------------------------------
    HS Ravensburg-Weingarten, Room T012          phone:  +49 (0) 751 501 9743
    Doggenriedstraße, 88250 Weingarten           (home)  +49 (0) 7504 2923511
    home: Furth 10, 88263 Horgenzell             mobile: +49 (0) 176 99625520
    mailto:scherzer@hs-weingarten.de                     +43 (0) 664  8709246
    http://portal.hs-weingarten.de/web/scherzer        skype: daniel.scherzer
-----------------------------------------------------------------------------

**Comment by Andi-Lo** [comment]
Danke für den Fix, jetzt funktioniert es bei mir :)

**Comment by danielscherzer** [comment]
gerne! :)

Am 21.10.2015 um 15:47 schrieb Andreas Lorer:
> Danke für den Fix, jetzt funktioniert es bei mir :)
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/danielscherzer/MMPROG/issues/1#issuecomment-149901337
>

-- 
-- Daniel Scherzer ----------------------------------------------------------
    HS Ravensburg-Weingarten, Room T012          phone:  +49 (0) 751 501 9743
    Doggenriedstraße, 88250 Weingarten           (home)  +49 (0) 7504 2923511
    home: Furth 10, 88263 Horgenzell             mobile: +49 (0) 176 99625520
    mailto:scherzer@hs-weingarten.de                     +43 (0) 664  8709246
    http://portal.hs-weingarten.de/web/scherzer        skype: daniel.scherzer
-----------------------------------------------------------------------------
