### ISSUE TITLE
Fehler beim Starten

### ISSUE THREAD

**Issue by Death111** [danielscherzer/MMPROG#10]
Wenn man das Tool startet und in einem Shader ein Fehler existiert, so wird dieser nicht angezeigt und nur ein graues bild dargestellt.
Dies geschieht nur wenn man mehr als einen Shader in der timeline hat. Bei nur einem Shader wird der fehler korrekt angezeigt.
![no_err](https://cloud.githubusercontent.com/assets/5772511/13258244/b80c2f3e-da52-11e5-9408-ce3f57994bd4.PNG)

**Comment by danielscherzer** [comment]
sollte erledigt sein.
