### ISSUE TITLE
Crash beim löschen eines Shaders

### ISSUE THREAD

**Issue by Death111** [danielscherzer/MMPROG#11]
Wenn man einen Shader per "rechtsklick" löscht, so stürzt das Tool ab:

![shader_remove](https://cloud.githubusercontent.com/assets/5772511/13258497/a8814df0-da53-11e5-8c94-20d9a365127b.PNG)
`Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.InvalidOperationException: Die Auflistung wurde geändert, nachdem der Enumerator instantiiert wurde.
   bei System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   bei System.Collections.Generic.SortedSet`1.Enumerator.MoveNext()
   bei System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   bei ShaderForm.ShaderKeyframes.RemoveAllWithName(String shaderFileName) in C:\Users\Death\Documents\MMPROG\ShaderForm\ShaderKeyframes.cs:Zeile 89.
   bei ShaderForm.FormMain.MenuShader_MouseDown(Object sender, MouseEventArgs e) in C:\Users\Death\Documents\MMPROG\ShaderForm\FormMain.cs:Zeile 391.
   bei System.Windows.Forms.ToolStripItem.RaiseMouseEvent(Object key, MouseEventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseDown(MouseEventArgs e)
   bei System.Windows.Forms.ToolStrip.OnMouseDown(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

**Comment by danielscherzer** [comment]
sollte erledigt sein.
