### ISSUE TITLE
Falsche 'ratios' beim starten mit Musik

### ISSUE THREAD

**Issue by Death111** [danielscherzer/MMPROG#12]
Wenn man Musik in seiner Demo verwendet und die shader entsprechend anordnet werden diese beim erneuten Starten falsch geladen.
Problem wird sein, dass er beim starten des Tools in ShaderKeyframes.cs in CalculateRatios(float length) mit length = 100 springt und nicht mit der Länge der Musik.

Abhilfe schafft nach Start des Tools die gleiche Demo erneut zu laden (str+o). Dort wird dann CalculateRatios mit der richtigen length aufgerufen.

**Comment by danielscherzer** [comment]
sollte erledigt sein.
