### ISSUE TITLE
FlyCam

### ISSUE THREAD

**Issue by Death111** [danielscherzer/MMPROG#6]
Wär hilfreich wenn man in seinem raymarching-shader mit wasd+maus fliegen und sich umschauen könnte.

Die ständige Anpassung von camPos und camDir ist etwas umständlich, wenn man seine Scene aufbaut.
Man müsste camPos und die °-Rotation der Kamera wohl per uniform mitgeben.

(Wie vergeb ich der Issue den nen label? Kannst das nur du Daniel?)

**Comment by danielscherzer** [comment]
hm ich denke darüber nach wie man das allgemeiner machen könnte: was hältst du davon dass es ein uniform array gibt, für eine tast e ein eintrag und dieser eintrag git an wielange diese taste insgesamt schon geddrückt worden ist. bsp.: 'w' taste ersten zehn sekunden bleibt es auf 0.0 weil nicht gedrückt dann drückt er sie für zwei sekunden der wert im feld ist danach bei 2.0; einige zeit später wird die taste nochmal für 0.5 sekunden gedrückt und der wert ist danach auf 2.5 hochgegangen. das kann man dann für absolute bewegungen z.b. der camera oder anderes verwenden.

**Comment by Death111** [comment]
Ich sag mal als 'fly-cam' kann man das System nicht nutzen(bzw. sehr eingeschränkt), da man ja nur absolute Werte hat.

Dein System wär eher was, wenn man den Shader fertig hat und dann userinput einbauen wollte. Aber denke ich nicht das sich das lohnt, da man im Shader nur eingeschränkt darauf reagieren kann (wie du sagst, dinge absolut bewegen).

**Comment by danielscherzer** [comment]
hm... bei ner flycam würdest du doch von aussen z.b. ne camPos übergeben. diese wird so erstellt, dass irgendwo code z.b. sowas wie <a> camPos.x += timePressedKey('d') </a> macht. das vorgeschlagene system würde genau sowas machen, aber halt in einer float variable per taste. müßte das nicht mindestens die funktionalität von <a> liefern?

**Comment by Death111** [comment]
Wenn ich ja nach vorne drück (W) und mich dann umdrehen würde (mit maus) dann müsste ich ja wieder zurück fliegen(W) und nicht rückwärts. Also eigentlich ja camPos += camDir * timePressedKey("w") ;

**Comment by danielscherzer** [comment]
ja verstehe; das geht damit nicht; ich dachte mir sowas wie wasd steurt die x und z koordinaten und mit der maus schaut man in ne richtung (was aber die bewegungsrichtung nicht ändert) hm; ist die flycam soviel praktischer?

**Comment by Death111** [comment]
Ist man halt aus anderen 3D Umgebungen gewohnt (Blender, Unity..).
Fänds praktischer  ;)

**Comment by kevinkl** [comment]
Fände die Funktion auch nützlich, falls das keine Umstände macht.

**Comment by Death111** [comment]
Hab das bei ihm gesehen https://youtu.be/T-9R0zAwL7s?t=1638 . Kann coden und muss dann zum anschauen nicht immer wieder in die main scrollen um kamera pos und dir anzupassen :)
