### ISSUE TITLE
FlyCam Keyframes

### ISSUE THREAD

**Issue by Death111** [danielscherzer/MMPROG#8]
Man sollte durch Verwendung der Flycam Keyframes setzen können, um so 'schöne' Kamerafahrten erstellen zu können.

**Comment by danielscherzer** [comment]
ja das kann ich schon einbauen. muss nur noch überlegen wie das sinn macht.
wenn man automatisch die camera keyframes mit der bewegung von maus und wasd mitschreibt, dann kriegt man sehr viele keyframes die man eigentlich nicht will. wenn man aber sowas wie nen button für übernahme von momentanen kamera einstellungen zu den keframes macht... so wie das jetzt ist, hätte man dann zwei instancen von camera steuernden uniforms: einmal die die vom keyframe form etc kommen und einmal die die direkt von maus und tastatur gesetzt werden. man will aber nur eine. mal schauen ob das ohne konflikte bzw unlogische schritte geht...

**Comment by Death111** [comment]
Jo, ich hatte mir das Keyframe setzen der Kamera auf ne Taste gelegt und im Shader in der main bei Bedarf die keyframes verwendet, indem ich die uniforms iCamPos und iCamRot 'überschrieben' hatte. Automatisches keyframe setzen ist nicht gut ja ;)

```
// flycam uniforms
uniform vec3 iCamPos;
uniform vec3 iCamRot;

// keyframed cam uniforms
uniform float iCamPosX;
uniform float iCamPosY;
uniform float iCamPosZ;
uniform float iCamRotX;
uniform float iCamRotY;

......

#define USE_KEYFRAMES // comment if u want to use flycam
void main()
{	
	float fov = 80.0;
	float tanFov = tan(fov / 2.0 * 3.14159 / 180.0) / iResolution.x;
	vec2 p = tanFov * (gl_FragCoord.xy * 2.0 - iResolution.xy);
	
	#ifdef USE_KEYFRAMES
	vec3 iCamPos = vec3(iCamPosX, iCamPosY, iCamPosZ);
	vec3 iCamRot = vec3(iCamRotX, iCamRotY,0);
	#endif
	
	vec3 camP = iCamPos;// vec3(0.0, 4, 10);
	vec3 camDir = normalize(vec3(p.x, p.y, 1.0));
	pR(camDir.yz, iCamRot.x);
	pR(camDir.xz, iCamRot.y);
	.......
```

Aber theoretisch wär es wohl besser, wenn man immer die keyframes verwendet und wenn man die demo pausiert man die flycam nutzen kann und diese Änderung dann an der aktuellen Stelle als Keyframe erstellt/überschreibt.

**Comment by danielscherzer** [comment]
done

**Comment by Death111** [comment]
Wenn man pausiert, sollte die flycam an der stelle sein, die sie davor hatte (durch die keyframes). Das man die kamera von der aktuellen stelle weiteranimieren kann, ohne erst die stelle zu finden, wo man pausiert hat :)

**Comment by danielscherzer** [comment]
done
